# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    rust: "latest"
  commands:
    - curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.5.2/mdbook-v0.5.2-x86_64-unknown-linux-gnu.tar.gz | tar -xz
    - ./mdbook build
    - mkdir -p $READTHEDOCS_OUTPUT/html
    - cp -r book/* $READTHEDOCS_OUTPUT/html/
